

export const VIEW_PRODUCT = 'VIEW_PRODUCT'
export const DELETE_PRODUCT_BY_CATEGORY = 'DELETE_PRODUCT_BY_CATEGORY'
// export const SELECTED_PRODUCT = 'SELECTED_PRODUCT'
// export const REMOVE_SELECTED_PRODUCT = 'REMOVE_SELECTED_PRODUCT'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY'

